### ISSUE TITLE
NPE when changing planned value on budgets worksheet

### ISSUE THREAD

**Issue by hoogenbj** [hoogenbj/countary#2]
Stacktrace:
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.profileMap" is null
	at hoogenbj.countary@1.0.2/hoogenbj.countary.app.BudgetItemWorksheetController.lambda$onPlannedChange$21(Unknown Source)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at hoogenbj.countary@1.0.2/hoogenbj.countary.app.BudgetItemWorksheetController.onPlannedChange(Unknown Source)
	at hoogenbj.countary@1.0.2/hoogenbj.countary.model.BudgetItemHolder.lambda$new$1(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@19.0.2.1/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@19.0.2.1/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base@19.0.2.1/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.base@19.0.2.1/javafx.beans.property.ObjectProperty.setValue(Unknown Source)
	at javafx.controls@19.0.2.1/javafx.scene.control.TableColumn.lambda$new$1(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@19.0.2.1/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.controls@19.0.2.1/javafx.scene.control.TableCell.commitEdit(Unknown Source)
	at javafx.controls@19.0.2.1/javafx.scene.control.cell.CellUtils.lambda$createTextField$1(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@19.0.2.1/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@19.0.2.1/javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.controls@19.0.2.1/com.sun.javafx.scene.control.behavior.TextFieldBehavior.fire(Unknown Source)
	at javafx.controls@19.0.2.1/com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$keyMapping$62(Unknown Source)
	at javafx.controls@19.0.2.1/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@19.0.2.1/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@19.0.2.1/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@19.0.2.1/javafx.scene.Scene$KeyHandler.process(Unknown Source)
	at javafx.graphics@19.0.2.1/javafx.scene.Scene.processKeyEvent(Unknown Source)
	at javafx.graphics@19.0.2.1/javafx.scene.Scene$ScenePeerListener.keyEvent(Unknown Source)
	at javafx.graphics@19.0.2.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
	at javafx.graphics@19.0.2.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@19.0.2.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(Unknown Source)
	at javafx.graphics@19.0.2.1/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@19.0.2.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(Unknown Source)
	at javafx.graphics@19.0.2.1/com.sun.glass.ui.View.handleKeyEvent(Unknown Source)
	at javafx.graphics@19.0.2.1/com.sun.glass.ui.View.notifyKey(Unknown Source)

**Comment by hoogenbj** [comment]
Fixed in 1.0.3 release
